SRC_URI:append = " \
	file://0000-compulab-imx9-Add-ucm-imx93-board-support.patch \
	file://0001-compulab-imx9-Update-ucm-imx93-files.patch \
	file://0002-compulab-imx9-Update-ucm-imx93-files.patch \
	file://0003-ucm-imx93-dts-Update-device-tree-files.patch \
	file://0004-ucm-imx93-board-Remove-unused-stuff.patch \
	file://0005-ucm-imx93-config-Remove-unused-stuff.patch \
	file://ucm-imx93_defconfig \
"
