SRC_URI:append = " \
	file://0000-compulab-imx9-Add-ucm-imx93-board-support.patch \
	file://0001-compulab-imx9-Update-ucm-imx93-files.patch \
	file://0002-compulab-imx9-Update-ucm-imx93-files.patch \
	file://0003-ucm-imx93-dts-Update-device-tree-files.patch \
	file://0004-ucm-imx93-board-Remove-unused-stuff.patch \
	file://0005-ucm-imx93-config-Remove-unused-stuff.patch \
	file://0006-drivers-phy-Fix-mergre-issue.patch \
	file://0007-drivers-video-nxp-Fix-mergre-issue.patch \
	file://0008-drivers-video-startek-ili9881c-Add-.plat_auto-.data.patch \
	file://0009-ucm-imx93-dts-Add-mipi-dsi-display.patch \
	file://0010-ucm-imx93-config-Update-defconfig.patch \
	file://0011-ucm-imx93-Add-compulab-imx93.h.patch \
	file://0012-ucm-imx93-Move-default-values-to-the-board-Kconfig.patch \
	file://0013-compulab-imx93-Remove-all-stdout-stdin-stderr.patch \
	file://0014-drivers-video-startek-ili9881c-Add-ili9881c_panel_of.patch \
	file://0015-ucm-imx93-dts-Remove-u-boot-lcdif-clocks.patch \
	file://0016-ucm-imx93-dts-Update-panel-node.patch \
	file://0017-drivers-video-startek-ili9881c-Update-panel-timing.patch \
	file://0018-drivers-video-startek-ili9881c-Suppress-debug-prints.patch \
	file://ucm-imx93_defconfig \
"
