SRC_URI:append = " \
           file://0001-remove-lcdif.patch \
           file://0002-Update-defconfig.patch \
           file://0009-mach-imx-Turn-the-imx_get_mac_from_fuse-into-a-weak.patch \
           file://0014-Add-compulab-baoards.patch \
           file://0012-nxp-video-imx_lcdifv3-CompuLab-update.patch \
           file://0015-imx_lcdifv3-Disable-display_enable-call.patch \
           file://0003-compulab-arch-arm-dts-Makefile.patch \
           file://0006-compulab-arch-arm-mach-imx-imx8m-clock_imx8mm.c.patch \
           file://0005-compulab-arch-arm-mach-imx-imx8m-Kconfig.patch \
           file://0007-imx8m-Disable-fixup_thermal_trips.patch \
           file://0013-efi-Disable-efi_net_register.patch \
           file://0004-compulab-arch-arm-include-asm-arch-imx8m-imx8mm_pins.patch \
           file://0008-compulab-Add-imx93-family.patch \
           file://0010-driver-pca9555-20-add-delay-to-eliminate-Error-of-re.patch \
           file://0011-drivers-video-Add-VIDEO_LCD_STARTEK_ILI9881C.patch \
           file://0016-ucm-imx93-2024.04-patch.patch \
           file://0017-ucm-imx93-Fix-a-typo.patch \ 
	   file://0018-compulab-ucm-imx91-Add-board-support.patch \
"
