require conf/machine/include/imx-base.inc
require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
require compulab-imx9.inc

# One production image for UCM-i.MX93 and MCM-i.MX93. U-Boot selects the
# matching Linux device tree from the module EEPROM at runtime.
MACHINE_FEATURES += "pci wifi bluetooth"
MACHINE_FEATURES:append:use-nxp-bsp = " optee jailhouse "

KERNEL_DEVICETREE_BASENAME = "ucm-imx93"
KERNEL_DEVICETREE = " \
    compulab/ucm-imx93.dtb \
    compulab/ucm-imx93-mipi.dtb \
    compulab/ucm-imx93-headless.dtb \
    compulab/ucm-imx93-mipi-csi.dtb \
    compulab/ucm-imx93-eb-eth.dtb \
    compulab/ucm-imx93-ml.dtb \
    compulab/sbc-mcm-imx93.dtb \
    compulab/sbc-mcm-imx93-ml.dtb \
    compulab/sbc-mcm-imx93-mipi-csi.dtb \
"

UBOOT_DEVICETREE_BASENAME = "cl-imx93"
UBOOT_DTB_NAME = "${UBOOT_DEVICETREE_BASENAME}.dtb"

IMX_DEFAULT_BOOTLOADER:use-nxp-bsp = "u-boot-compulab"
IMX_DEFAULT_BOOTLOADER:use-mainline-bsp = "u-boot-compulab"

LOADADDR = ""
UBOOT_SUFFIX = "bin"
UBOOT_MAKE_TARGET = ""

SPL_BINARY = "spl/u-boot-spl.bin"

UBOOT_CONFIG_BASENAME = "cl-imx93"
EXTRA_OEMAKE:append:pn-u-boot-compulab = " DEVICE_TREE=${UBOOT_DEVICETREE_BASENAME} ENV_SOURCE_FILE=imx93"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_CONFIG_IMAGE_FSTYPES[sd] = "sdcard"

ATF_PLATFORM = "imx93"

IMXBOOT_TARGETS = "flash_singleboot"
IMX_BOOT_SOC_TARGET = "iMX9"
IMX_BOOT_SEEK = "32"

SERIAL_CONSOLES = "115200;ttyLP0"

MACHINE_FIRMWARE:append = " ethos-u-firmware linux-firmware-sd8997 "

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"

SECO_FIRMWARE_NAME:mx9-nxp-bsp = "mx93a0-ahab-container.img"

IMAGE_BOOT_FILES:append:use-nxp-bsp = " \
    imx93_m33_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    imx93_m33_TCM_rpmsg_lite_str_echo_rtos.bin \
"
WKS_FILE_DEPENDS:append = " imx-m33-demos"

CL_RELEASE = "3.1"
