SRC_URI:append = " \
	file://0000-compulab-imx9-Add-ucm-imx93-board-support.patch \
	file://0001-ucm-imx93-dts-draft-00.patch \
	file://0002-ucm-imx93-dts-draft-pmic.patch \
	file://0003-ucm-imx93-dts-Add-ethernet-aliases.patch \
	file://0004-video-draft-00.patch \
	file://0005-video-draft-01.patch \
	file://0006-video-draft-02.patch \
	file://0007-rtc-draft-00.patch \
	file://0008-wifi-draft-00.patch \
	file://defconfig \
"
